</usr/share/alsa/alsa.conf>

pcm.pico_gain {
    type softvol
    slave {
        pcm "hw:Microphone,0"
    }
    control {
        name "Pico Capture Gain"
        card "Microphone"
    }
    min_dB 0.0
    max_dB 30.0
    resolution 121
}
